# Generated by Django 4.2.6 on 2023-12-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('formacao', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
