# Generated by Django 4.2.6 on 2023-12-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_leitor_anuncio_favoritado_texto_favoritado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='texto',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='texto',
            name='resumo',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=500)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.texto')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
            ],
        ),
    ]
